name: Build MSP430

on:
  push:
    branches: [ "main", "dev" ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subproject:
          #- msp430_deep_sleep
          - msp430_spi_fram
          #- msp430_testable
    env:
      MSP_GNU_ROOT: ""${{ github.workspace }}/msp430-gcc"

    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v3

    - name: Install dependencies ğŸ”§
      run: sudo apt update && sudo apt install -y p7zip build-essential wget

    - name: Download TI's MSP gcc toolchain ğŸ”½
      run: wget https://dr-download.ti.com/software-development/ide-configuration-compiler-or-debugger/MD-LlCjWuAbzH/9.3.1.2/msp430-gcc-full-linux-x64-installer-9.3.1.2.7z
      # updates: https://www.ti.com/tool/MSP430-GCC-OPENSOURCE#downloads

    - name: Unpack with 7zip ğŸ“¦
      run: 7zr x msp430-gcc-full-linux-x64-installer-9.3.1.2.7z

    - name: Run the installer ğŸƒ
      run: sudo ./msp430-gcc-full-linux-x64-installer-9.3.1.2.run --mode unattended --prefix ${{ env.MSP_GNU_ROOT }}

    - name: Build the project "${{ matrix.subproject }}" ğŸ§±
      run: make
      working-directory: "${{ github.workspace }}/${{ matrix.subproject }}"

    - name: Upload artifacts to github ğŸ”¼
      uses: actions/upload-artifact@v3
      with:
        name: "${{ matrix.subproject }}"
        path: "${{ github.workspace }}/${{ matrix.subproject }}/_build/build.hex"
